### PR TITLE
fixed channel prefix

### PR DESCRIPTION
**Pull request by Betriebsrat**
rest is tabs being replaced by spaces (pycharm)

### CODE REVIEW

**Review by Vaelor — CHANGES_REQUESTED** [review]
Thank you very much for the contribution!

I have to ask you to revert the 'syntax' commit.
In my opinion, commits which change the whole file changing just whitespaces aren't optimal.
They clutter the history with (IMHO) unimportant changes.
Also, the choice for tabs was made with the knowledge that I do not adhere to the widely used PEP 8 style recommendations and I would like to keep it that way.
Yes, it is just my personal preference :-)

Oh the spaces in the other commit should be tabs, too.

**Comment by Betriebsrat** [comment]
https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/

**Comment by gbin** [comment]
Haha @bitriebsrat, this will become my standard tab response ;)

**Comment by Vaelor** [comment]
Well it still would not change my opinion, but the study is interesting - I would fit in the 'both' faction, which in Europe does not make such a big difference :-)
No, but honestly: I have no problem working with either spaces or tabs in projects of other people - but personally I prefer tabs, for various (also subjective) reasons.
I do not want a tabs vs spaces discussion, as this would lead nowhere.
I would be happy if my decision would be accepted. If not - that's okay, too, but I wouldn't change it. ;-)

**Comment by Betriebsrat** [comment]
No need to discuss anything. Personal preference is fine. 
Just delete the pull request and change the char in your master then. Too much effort for me to revert everything for this.

**Comment by Vaelor** [comment]
Okay thanks. I did not want to do that, I thought it would be rude if I just went ahead and changed something you made a PR for - Well, thanks for spotting the error :)

**Pull request closed without merging**
